Repository PeopleForBikes/brokenspoke-analyzer, pull requests merged in 2023-08, with the labels that each got.

#257 Reorganize the internal API
  .github/workflows/ci.yaml
  brokenspoke_analyzer/cli.py
  brokenspoke_analyzer/core/aiohttphelper.py
  brokenspoke_analyzer/core/analysis.py
  brokenspoke_analyzer/core/downloader.py
  brokenspoke_analyzer/core/runner.py
  brokenspoke_analyzer/core/srid.py
  brokenspoke_analyzer/core/utils.py
  docs/source/api/brokenspoke_analyzer.core.analysis.rst
  docs/source/api/brokenspoke_analyzer.core.downloader.rst
  docs/source/api/brokenspoke_analyzer.core.rst
  docs/source/api/brokenspoke_analyzer.core.runner.rst
  docs/source/api/brokenspoke_analyzer.core.srid.rst
  docs/source/api/brokenspoke_analyzer.core.utils.rst
  docs/source/api/brokenspoke_analyzer.rst
  docs/source/conf.py
  docs/source/index.rst
  poetry.lock
  pyproject.toml
Labels: size/XL

#259 Remove GDAL dependency
  .github/workflows/ci.yaml
  brokenspoke_analyzer/core/srid.py
  brokenspoke_analyzer/core/utils.py
  docs/source/api/brokenspoke_analyzer.core.rst
  docs/source/api/brokenspoke_analyzer.core.srid.rst
  poetry.lock
  pyproject.toml
Labels: size/L, do-not-merge

#272 Remove partial downloads and add retries
  brokenspoke_analyzer/cli.py
  poetry.lock
  pyproject.toml
Labels: size/M

#280 Update dependencies
  poetry.lock
  pyproject.toml
Labels: size/XS

#282 Enable MyPy for the cli.py module
  .gitignore
  brokenspoke_analyzer/cli.py
  brokenspoke_analyzer/core/analysis.py
  brokenspoke_analyzer/core/runner.py
  pyproject.toml
Labels: size/L

#283 Update installation instructions to use tags
  README.md
Labels: size/M

#284 prepare release
  CHANGELOG.md
  README.md
  pyproject.toml
Labels: size/S

#285 Attempt to fix poetry/numpy
  poetry.lock
  pyproject.toml
Labels: size/XS

#274 Reorganize CLI
  brokenspoke_analyzer/cli/__init__.py
  brokenspoke_analyzer/cli/common.py
  brokenspoke_analyzer/cli/export.py
  brokenspoke_analyzer/cli/importer.py
  brokenspoke_analyzer/cli/prepare.py
  brokenspoke_analyzer/cli/root.py
  brokenspoke_analyzer/cli_.py
  brokenspoke_analyzer/main.py
  pyproject.toml
Labels: size/L

#265 Rewrite the import neighborhood script in Python
  Dockerfile
  brokenspoke_analyzer/cli/common.py
  brokenspoke_analyzer/cli/configure.py
  brokenspoke_analyzer/cli/importer.py
  brokenspoke_analyzer/cli/prepare.py
  brokenspoke_analyzer/cli/root.py
  brokenspoke_analyzer/core/analysis.py
  brokenspoke_analyzer/core/constant.py
  brokenspoke_analyzer/core/database/__init__.py
  brokenspoke_analyzer/core/database/dbcore.py
  brokenspoke_analyzer/core/downloader.py
  brokenspoke_analyzer/core/ingestor.py
  brokenspoke_analyzer/core/runner.py
  brokenspoke_analyzer/core/utils.py
  compose-config/servers.json
  compose.yml
  integration/e2e.md
  integration/ingestor.py
  justfile
  poetry.lock
  pyproject.toml
  scripts/mapconfig_cycleway.xml
  scripts/mapconfig_highway.xml
  scripts/pfb.style
  scripts/sql/create_us_water_blocks_table.sql
  scripts/sql/speed_tables.sql
Labels: size/XXL
