Repository PeopleForBikes/brokenspoke-analyzer, pull requests merged in 2023-11, with the labels that each got.

#413 Replaces Black with Ruff
  justfile
  poetry.lock
  pyproject.toml
Labels: size/XS

#422 Update the documentation
  CHANGELOG.md
  docs/source/_static/brokenspoke-analyzer-architecture.svg
  docs/source/about.md
  docs/source/index.rst
  docs/source/usage.md
Labels: size/L

#432 Update the documentation
  brokenspoke_analyzer/core/ingestor.py
  docs/source/about.md
  docs/source/commands.md
  docs/source/datasets.rst
  docs/source/index.rst
  docs/source/regions.rst
  docs/source/resources.rst
  integration/e2e.md
  poetry.lock
  tests/test_brokenspoke_analyzer.py
Labels: size/XXL

#433 Review API docs
  brokenspoke_analyzer/__init__.py
  brokenspoke_analyzer/cli/__init__.py
  brokenspoke_analyzer/cli/common.py
  brokenspoke_analyzer/cli/configure.py
  brokenspoke_analyzer/cli/export.py
  brokenspoke_analyzer/cli/importer.py
  brokenspoke_analyzer/cli/prepare.py
  brokenspoke_analyzer/cli/root.py
  brokenspoke_analyzer/cli/run_with.py
  brokenspoke_analyzer/core/__init__.py
  brokenspoke_analyzer/core/analysis.py
  brokenspoke_analyzer/core/compute.py
  brokenspoke_analyzer/core/database/dbcore.py
  brokenspoke_analyzer/core/exporter.py
  brokenspoke_analyzer/core/ingestor.py
  brokenspoke_analyzer/core/runner.py
  brokenspoke_analyzer/core/utils.py
  brokenspoke_analyzer/pyrosm/data/__init__.py
  docs/source/api/brokenspoke_analyzer.core.compute.rst
  docs/source/api/brokenspoke_analyzer.core.database.dbcore.rst
  docs/source/api/brokenspoke_analyzer.core.database.rst
  docs/source/api/brokenspoke_analyzer.core.exporter.rst
  docs/source/api/brokenspoke_analyzer.core.ingestor.rst
  docs/source/api/brokenspoke_analyzer.core.rst
  docs/source/api/brokenspoke_analyzer.rst
  pyproject.toml
Labels: size/L

#434 Update Quickstart Instructions
  README.md
Labels: size/S
