Repository PeopleForBikes/brokenspoke-analyzer, pull requests merged in 2023-10, with the labels that each got.

#366 Trim down the CLI
  brokenspoke_analyzer/cli/importer.py
  brokenspoke_analyzer/cli/prepare.py
  brokenspoke_analyzer/cli/root.py
  brokenspoke_analyzer/cli/run_with.py
  brokenspoke_analyzer/core/analysis.py
  brokenspoke_analyzer/core/ingestor.py
Labels: size/L

#369 Configure loguru to use RichHandler
  brokenspoke_analyzer/cli/root.py
  brokenspoke_analyzer/core/analysis.py
Labels: size/S

#371 Update Kodiak configuration
  .github/.kodiak.toml
Labels: size/XS

#370 Log subprocess outputs
  brokenspoke_analyzer/core/runner.py
Labels: size/S

#372 Update the dependencies
  Dockerfile
  poetry.lock
  pyproject.toml
Labels: size/XS

#373 Prepare codebase for 2.0.0-beta release
  pyproject.toml
Labels: size/XS

#374 Update Docker environment
  Dockerfile
  brokenspoke_analyzer/core/database/dbcore.py
  compose.yml
  compose/Dockerfile
Labels: size/S

#377 Implement S3 exporter
  brokenspoke_analyzer/cli/export.py
  brokenspoke_analyzer/cli/prepare.py
  brokenspoke_analyzer/cli/run_with.py
  brokenspoke_analyzer/core/exporter.py
  integration/e2e.md
  justfile
  poetry.lock
  pyproject.toml
Labels: size/L

#378 Add database configuration sub-commands
  brokenspoke_analyzer/cli/configure.py
  brokenspoke_analyzer/core/database/dbcore.py
Labels: size/L

#382 Add sdist and wheel to the Release assets (#339)
  .github/workflows/release.yaml
Labels: size/S

#383 Add --export flag to the run command
  brokenspoke_analyzer/cli/root.py
  brokenspoke_analyzer/cli/run_with.py
  brokenspoke_analyzer/core/exporter.py
Labels: size/S

#384 Prepare codebase for 2.0.0-rc tagging
  README.md
  integration/e2e.md
  pyproject.toml
Labels: size/S

#391 Remove poetry export from Dockerfile
  .github/workflows/prerelease.yaml
  .github/workflows/release.yaml
  Dockerfile
  requirements.txt
Labels: size/M

#392 Fix Docker Compose
  compose.yml
Labels: size/XS

#393 Add parameter to specify the S3 bucket name
  brokenspoke_analyzer/cli/root.py
  brokenspoke_analyzer/cli/run_with.py
  brokenspoke_analyzer/core/exporter.py
Labels: size/S

#406 Update dependencies
  .gitignore
  Dockerfile
  poetry.lock
  requirements.txt
Labels: size/S
