Repository PeopleForBikes/brokenspoke-analyzer, pull requests merged in 2023-09, with the labels that each got.

#303 Fix Docker container
  Dockerfile
  brokenspoke_analyzer/core/analysis.py
  integration/e2e.md
  justfile
  requirements.txt
Labels: size/XL

#294 Rewrite the export script to Python
  .env
  .gitignore
  brokenspoke_analyzer/cli/common.py
  brokenspoke_analyzer/cli/export.py
  brokenspoke_analyzer/core/compute.py
  brokenspoke_analyzer/core/database/dbcore.py
  brokenspoke_analyzer/core/exporter.py
  brokenspoke_analyzer/core/ingestor.py
  brokenspoke_analyzer/core/runner.py
  brokenspoke_analyzer/database/__init__.py
  brokenspoke_analyzer/database/dbcore.py
  integration/e2e.md
Labels: size/L

#305 Implement the run sub-command
  brokenspoke_analyzer/cli/importer.py
  brokenspoke_analyzer/cli/root.py
  brokenspoke_analyzer/core/compute.py
  brokenspoke_analyzer/core/ingestor.py
  brokenspoke_analyzer/core/utils.py
  integration/e2e.md
  integration/e2e.py
Labels: size/L

#310 Implement run-with subcommand
  brokenspoke_analyzer/cli/common.py
  brokenspoke_analyzer/cli/root.py
  brokenspoke_analyzer/cli/run_with.py
  brokenspoke_analyzer/core/runner.py
  brokenspoke_analyzer/core/utils.py
Labels: size/L

#311 Add function to create SQLAlchemy psycopg engine
  brokenspoke_analyzer/cli/configure.py
  brokenspoke_analyzer/cli/importer.py
  brokenspoke_analyzer/cli/root.py
  brokenspoke_analyzer/cli/run_with.py
  brokenspoke_analyzer/core/compute.py
  brokenspoke_analyzer/core/database/dbcore.py
  brokenspoke_analyzer/core/exporter.py
  integration/e2e.py
Labels: size/M

#315 Implement a 'run-with compare' sub-command
  brokenspoke_analyzer/cli/common.py
  brokenspoke_analyzer/cli/export.py
  brokenspoke_analyzer/cli/run_with.py
  brokenspoke_analyzer/core/runner.py
  brokenspoke_analyzer/core/utils.py
  integration/e2e.py
  poetry.lock
  pyproject.toml
Labels: size/L

#316 Add e2e tests comparing results
  brokenspoke_analyzer/cli/prepare.py
  brokenspoke_analyzer/cli/run_with.py
  brokenspoke_analyzer/core/runner.py
  integration/e2e_compare.py
  pyproject.toml
Labels: size/L

#317 Refactor the CLI
  brokenspoke_analyzer/cli/common.py
  brokenspoke_analyzer/cli/export.py
  brokenspoke_analyzer/cli/importer.py
  brokenspoke_analyzer/cli/prepare.py
  brokenspoke_analyzer/cli/root.py
  brokenspoke_analyzer/cli/run_with.py
  brokenspoke_analyzer/cli_.py
  brokenspoke_analyzer/core/compute.py
  brokenspoke_analyzer/core/ingestor.py
  brokenspoke_analyzer/core/utils.py
  brokenspoke_analyzer/scripts/sql/stress/stress_segments_lower_order.sql
  integration/e2e.py
  integration/e2e_compare.py
Labels: size/XL

#318 Fix Typer annotations
  brokenspoke_analyzer/cli/prepare.py
  brokenspoke_analyzer/cli/run_with.py
Labels: size/S

#320 Implement various fixes
  brokenspoke_analyzer/cli/common.py
  brokenspoke_analyzer/cli/prepare.py
  brokenspoke_analyzer/cli/run_with.py
  brokenspoke_analyzer/core/database/dbcore.py
  brokenspoke_analyzer/core/downloader.py
  brokenspoke_analyzer/core/ingestor.py
  brokenspoke_analyzer/core/runner.py
  brokenspoke_analyzer/core/utils.py
  brokenspoke_analyzer/scripts/sql/clip_osm.sql
  brokenspoke_analyzer/scripts/sql/features/functional_class.sql
  brokenspoke_analyzer/scripts/sql/features/rrfb.sql
  brokenspoke_analyzer/scripts/sql/features/signalized.sql
  brokenspoke_analyzer/scripts/sql/stress/stress_segments_higher_order.sql
  brokenspoke_analyzer/scripts/sql/stress/stress_segments_lower_order_res.sql
  integration/e2e_compare.py
Labels: size/XL

#319 Add log for download retries
  brokenspoke_analyzer/cli/prepare.py
Labels: size/XS

#321 issues/299/integration tests ci
  .github/dependabot.yml
  .github/workflows/e2e.yaml
  brokenspoke_analyzer/cli/run_with.py
  brokenspoke_analyzer/core/runner.py
  brokenspoke_analyzer/scripts/pfb.style
  brokenspoke_analyzer/scripts/sql/clip_osm.sql
Labels: size/M

#329 Add download validation
  brokenspoke_analyzer/cli/prepare.py
  brokenspoke_analyzer/core/utils.py
  brokenspoke_analyzer/pyrosm/data/__init__.py
Labels: size/M

#330 Update the documentation for v2.0.0
  README.md
  brokenspoke_analyzer/cli/configure.py
  brokenspoke_analyzer/cli/prepare.py
  docs/source/commands.md
  docs/source/conf.py
  docs/source/index.rst
  docs/source/usage.md
  docs/source/usage.rst
  justfile
Labels: size/XL

#341 Prepare codebase for 2.0.0-alpha release
  CHANGELOG.md
  README.md
  docs/source/commands.md
  pyproject.toml
Labels: size/M

#343 Adjust release CI tags
  .github/workflows/release.yaml
Labels: size/XS

#344 Fix release globs
  .github/workflows/release.yaml
Labels: size/XS

#345 Fix release globs
  .github/workflows/release.yaml
Labels: size/XS

#346 Revert release globs
  .github/workflows/release.yaml
Labels: size/XS

#348 Update dependencies
  poetry.lock
  pyproject.toml
Labels: size/XS

#347 Use "region" keyword instead of "state"
  brokenspoke_analyzer/cli/importer.py
  brokenspoke_analyzer/cli/prepare.py
  brokenspoke_analyzer/cli/root.py
  brokenspoke_analyzer/cli/run_with.py
  integration/e2e_compare.py
Labels: size/M

#349 Separate data and results directories
  .gitignore
  brokenspoke_analyzer/cli/common.py
  brokenspoke_analyzer/cli/export.py
  brokenspoke_analyzer/cli/run_with.py
Labels: size/M

#350 Add CI workflow to build and publish Docker images
  .github/workflows/release.yaml
Labels: size/XS

#351 Replace --speed-limit flag
  brokenspoke_analyzer/cli/prepare.py
  brokenspoke_analyzer/cli/root.py
  brokenspoke_analyzer/cli/run_with.py
  integration/e2e_compare.py
Labels: size/M

#352 Remove export "--force" flag
  brokenspoke_analyzer/cli/export.py
  brokenspoke_analyzer/cli/run_with.py
Labels: size/S

#359 Rename "census-year" CLI flag
  brokenspoke_analyzer/cli/common.py
  brokenspoke_analyzer/cli/importer.py
  brokenspoke_analyzer/cli/prepare.py
  brokenspoke_analyzer/cli/root.py
  brokenspoke_analyzer/cli/run_with.py
  brokenspoke_analyzer/core/ingestor.py
  integration/e2e.py
  integration/e2e_compare.py
Labels: size/M

#361 Add "--version" Option flag
  brokenspoke_analyzer/cli/root.py
Labels: size/M

#364 Make pgAdmin optional
  compose.yml
  compose/pgAdmin/compose-pgadmin.yml
  compose/pgAdmin/config/pgpass
  compose/pgAdmin/config/servers.json
Labels: size/M
