Repository PeopleForBikes/brokenspoke-analyzer, pull requests merged in 2024-03, with the labels that each got.

#518 Update exporter
  CHANGELOG.md
  brokenspoke_analyzer/cli/common.py
  brokenspoke_analyzer/cli/configure.py
  brokenspoke_analyzer/cli/export.py
  brokenspoke_analyzer/cli/importer.py
  brokenspoke_analyzer/cli/prepare.py
  brokenspoke_analyzer/cli/root.py
  brokenspoke_analyzer/core/analysis.py
  brokenspoke_analyzer/core/database/dbcore.py
  brokenspoke_analyzer/core/downloader.py
  brokenspoke_analyzer/core/exporter.py
  brokenspoke_analyzer/core/ingestor.py
  brokenspoke_analyzer/core/runner.py
  brokenspoke_analyzer/core/utils.py
  brokenspoke_analyzer/main.py
  docs/source/commands.md
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: size/L

#542 Update destinations OSM tags
  brokenspoke_analyzer/scripts/pfb.style
  brokenspoke_analyzer/scripts/sql/connectivity/destinations/dentists.sql
  brokenspoke_analyzer/scripts/sql/connectivity/destinations/doctors.sql
  brokenspoke_analyzer/scripts/sql/connectivity/destinations/hospitals.sql
  brokenspoke_analyzer/scripts/sql/connectivity/destinations/pharmacies.sql
  brokenspoke_analyzer/scripts/sql/connectivity/destinations/retail.sql
  brokenspoke_analyzer/scripts/sql/connectivity/destinations/schools.sql
Labels: size/M

#543 Prepare codebase for 2.1.0 release
  CHANGELOG.md
  pyproject.toml
Labels: size/S

#544 Fix release workflows
  .github/workflows/release.yaml
  CHANGELOG.md
  pyproject.toml
Labels: size/S

#545 Update release workflow
  .github/workflows/release.yaml
Labels: size/XS
