Repository PeopleForBikes/brokenspoke-analyzer, pull requests merged in 2024-07, with the labels that each got.

#652 Fix Dockerfile
  .github/workflows/release.yaml
  Dockerfile
Labels: size/S

#653 Prepare codebase for 2.2.1 release
  CHANGELOG.md
  pyproject.toml
Labels: size/M

#648 Change neighborhood_reachable_roads_low_stress to neighborhood_reachable_roads_high_stress in connected census blocks calculation
  brokenspoke_analyzer/scripts/sql/connectivity/connected_census_blocks.sql
Labels: size/XS

#654 Add indexes for intersection_to and intersection_from on neighborhood_ways
  brokenspoke_analyzer/scripts/sql/prepare_tables.sql
Labels: size/XS

#660 Reduce size of connected roads tables and indexes
  brokenspoke_analyzer/scripts/sql/connectivity/reachable_roads_high_stress_cleanup.sql
  brokenspoke_analyzer/scripts/sql/connectivity/reachable_roads_high_stress_prep.sql
  brokenspoke_analyzer/scripts/sql/connectivity/reachable_roads_low_stress_cleanup.sql
  brokenspoke_analyzer/scripts/sql/connectivity/reachable_roads_low_stress_prep.sql
Labels: size/S
