Repository PeopleForBikes/brokenspoke-analyzer, pull requests merged in 2025-03, with the labels that each got.

#832 Fix water block issues
  brokenspoke_analyzer/cli/prepare.py
  brokenspoke_analyzer/cli/root.py
  brokenspoke_analyzer/cli/run_with.py
  brokenspoke_analyzer/core/constant.py
  brokenspoke_analyzer/core/ingestor.py
  brokenspoke_analyzer/core/utils.py
  integration/e2e.py
Labels: size/M

#718 Add Dev container for local development
  .devcontainer/devcontainer.json
  .devcontainer/postAttach.sh
  .github/CONTRIBUTING.md
  Dockerfile
  compose.yml
  justfile
Labels: size/L

#837 Update dependencies
  Dockerfile
  README.md
  justfile
  pyproject.toml
  uv.lock
Labels: size/M

#839 Prepare 2.5.0 release
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: size/S
