Repository PeopleForBikes/brokenspoke-analyzer, pull requests merged in 2025-05, with the labels that each got.

#831 Calculate bike infra inventory
  brokenspoke_analyzer/core/compute.py
  brokenspoke_analyzer/core/constant.py
  brokenspoke_analyzer/core/database/dbcore.py
  brokenspoke_analyzer/core/exporter.py
  brokenspoke_analyzer/scripts/sql/features/calculate_mileage.sql
Labels: size/M

#856 Fix calver revision
  brokenspoke_analyzer/core/exporter.py
Labels: size/S

#857 Add documentation for `measure`
  docs/source/commands.md
Labels: size/XS

#860 Fix measure
  brokenspoke_analyzer/cli/root.py
  brokenspoke_analyzer/scripts/sql/features/calculate_mileage.sql
Labels: size/M

#861 Fix table export
  brokenspoke_analyzer/core/database/dbcore.py
Labels: size/XS

#854 Create a script to run a series of analysis.
  .gitignore
  README.md
  brokenspoke_analyzer/cli/common.py
  brokenspoke_analyzer/cli/configure.py
  brokenspoke_analyzer/cli/export.py
  brokenspoke_analyzer/cli/prepare.py
  brokenspoke_analyzer/cli/root.py
  brokenspoke_analyzer/cli/run_with.py
  brokenspoke_analyzer/core/ingestor.py
  justfile
  utils/bna-wrapper.py
Labels: size/L

#864 Fix Putrajaya, Malaysia
  brokenspoke_analyzer/cli/importer.py
  brokenspoke_analyzer/cli/prepare.py
  brokenspoke_analyzer/cli/run_with.py
  brokenspoke_analyzer/core/analysis.py
Labels: size/S
