Repository PeopleForBikes/brokenspoke-analyzer, pull requests merged in 2025-04, with the labels that each got.

#807 Use new format for street parking tagging
  brokenspoke_analyzer/scripts/pfb.style
  brokenspoke_analyzer/scripts/sql/features/park.sql
Labels: size/S

#824 Remove unused column and indices in neighborhood_connected_census_blocks table
  brokenspoke_analyzer/scripts/sql/connectivity/connected_census_blocks.sql
Labels: size/XS

#851 Normalize country name before building location slug in compute command
  brokenspoke_analyzer/cli/root.py
Labels: size/XS

#842 Use cache folder for downloads
  Dockerfile
  brokenspoke_analyzer/cli/prepare.py
  brokenspoke_analyzer/core/constant.py
  brokenspoke_analyzer/core/datastore.py
  brokenspoke_analyzer/core/downloader.py
  brokenspoke_analyzer/core/utils.py
  brokenspoke_analyzer/scripts/sql/connectivity/connected_census_blocks.sql
  brokenspoke_analyzer/scripts/sql/connectivity/overall_scores.sql
  brokenspoke_analyzer/scripts/sql/prepare_tables.sql
  docs/source/caching.md
  docs/source/conf.py
  docs/source/index.rst
  pyproject.toml
  tests/test_brokenspoke_analyzer.py
  utils/cache-warmer.py
  uv.lock
Labels: size/XL

#845 Add ability to run partial analysis
  .github/workflows/e2e.yaml
  brokenspoke_analyzer/cli/common.py
  brokenspoke_analyzer/cli/root.py
  brokenspoke_analyzer/cli/run_with.py
  brokenspoke_analyzer/core/compute.py
  brokenspoke_analyzer/core/constant.py
  brokenspoke_analyzer/core/database/dbcore.py
  brokenspoke_analyzer/core/exporter.py
  brokenspoke_analyzer/core/ingestor.py
  docs/source/commands.md
  tests/test_brokenspoke_analyzer.py
Labels: size/L
